### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by triandamai** [triandamai/bank-falah-syariah#42]
alasan :
The reason you're receiving that error is that you're using the runtime build which doesn't support templates in HTML files as seen here

cara benerin:

pakai `()=>import('.../...')` bukan `import('../..')`

**Comment by rochman25** [comment]
@triandamai siap , open issue dewek, comment dewek , solve dewek

**Comment by triandamai** [comment]
wkwkwk
mantep kan

**Comment by rochman25** [comment]
@triandamai mantap qaqa
