### ISSUE TITLE
after add/update pembiayaan eror in datatable

### ISSUE THREAD

**Issue by triandamai** [triandamai/bank-falah-syariah#46]
![image](https://user-images.githubusercontent.com/41132846/126331176-820f97f3-f71a-4774-ba9a-aeb3e4905154.png)

reason :
karena seharusnya object `nama_lengkap` berada didalam object `nasabah` 

possible solution:
setelah tambah/update `commit` ke datapembiayaan di bungkus object `nasabah` ex: `nasabah:{nama_lengkap:'nama'}`

**Comment by triandamai** [comment]
Akan di perbaikin dari sisi back-end oleh  @rochman25 confirmed 😄

**Comment by rochman25** [comment]
:(
