### ISSUE TITLE
client always fetch to server in detail rekening

### ISSUE THREAD

**Issue by rochman25** [triandamai/bank-falah-syariah#55]
when i check this link
https://bfs.bakaranproject.com/main/mutasi/simpanan/01100001

and go to console , i see unlimited fetch to server

**Comment by triandamai** [comment]
when i check what's wrong...then i realized that its part of `feature` not a bug 😄

**Comment by rochman25** [comment]
@triandamai Hey how the world that become feature

**Comment by triandamai** [comment]
🤣

**Comment by triandamai** [comment]
make `feature` become bug 🤣
