### ISSUE TITLE
validate all transaction

### ISSUE THREAD

**Issue by rochman25** [triandamai/bank-falah-syariah#56]
- [x]  return validation message from service when transaction is requested

**Comment by triandamai** [comment]
mksde?

**Comment by rochman25** [comment]
@triandamai Validasi semua, jika ada pesan error validasi dari server tampilkan

**Comment by triandamai** [comment]
Response nya sperti apa ?

**Comment by triandamai** [comment]
Give me an example

**Comment by rochman25** [comment]
@triandamai Example 

If you request to endpoint then your request is mention as bad request , service will generate message errors based on your request 

And this issue is to ensure that errors message is delivered and ensure client see and understand the error

**Comment by triandamai** [comment]
Aah seee

Its look like this ?
```json
{
   "message":"this is message",
   "errors":[]
}
```

**Comment by rochman25** [comment]
@triandamai yes thats right

**Comment by rochman25** [comment]
@triandamai i think the service need to update more validation too

**Comment by triandamai** [comment]
@rochman25 okay sounds great i'll add `http interceptor` in client side to handle these case

**Comment by triandamai** [comment]
C3mungud

**Comment by rochman25** [comment]
@triandamai sounds like a plan

**Comment by triandamai** [comment]
@rochman25 can you describe response for both error,and success ?
ex success:
```json
{
    "data": {
        "status": 201,
        "message": "Sukses",
        "total_data": 1,
        "count_data": 1,
        "data": {
            "data": [        ]
        }
    },
    "status": 201,
}
````

**Comment by triandamai** [comment]
issue related:
https://github.com/rochman25/aksioma_service/issues/33
