### ISSUE TITLE
update all transaksi again

### ISSUE THREAD

**Issue by rochman25** [triandamai/bank-falah-syariah#59]
- [x]  nomor rekening auto fillable based on nasabah
- [x]  if nasabah have more than 1 then nomor rekening become dropdown with list of rekening nasabah

**Comment by triandamai** [comment]
berarti auto fill rekening generate dari back end?

**Comment by rochman25** [comment]
@triandamai Bagusnya dari front end juga ehehe

**Comment by triandamai** [comment]
brrt bisa rekening yang  ke genrate ke nasabah yang sama?
